### ISSUE TITLE
Wiki HPOVApplianceTrustedCertificate wrong documentation

### ISSUE THREAD

**Issue by JaragonCR** [HewlettPackard/POSH-HPOneView-docs#9]
https://github.com/HewlettPackard/POSH-HPOneView/wiki/Add-HPOVApplianceTrustedCertificate

```
Description
Hypervisor Manager is software for managing virtualized environments. Through the HPE OneView Hypervisor Manager resource, you can create, import, configure, and manage hypervisors and hypervisor clusters. A hypervisor manager provides the hostname and credentials to register with HPE OneView. HPE OneView uses these details to communicate with a hypervisor manager to perform tasks such as add, edit, and remove hypervisors or hypervisor clusters.
```

**Comment by ChrisLynchHPE** [comment]
This project is where user documentation bugs need to be reported.  I'll get this fixed, as this clearly is not correct.

**Comment by ChrisLynchHPE** [comment]
This was just fixed and pushed into the master branch.  It will take a few minutes for the doc tool to pull all of the changes.

**Comment by ChrisLynchHPE** [comment]
In fact, the changes were just now pulled, and the corrected doc is now live.  Closing.
